analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3485958,"name"\:"PROMEDO-WEB","teamId"\:3476248,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3500952,"sampleProject"\:false,"autoIntegrate"\:false,"accountId"\:null}
analytics.team={"id"\:3476248,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
