<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AutomaticPayments-actives</name>
   <tag></tag>
   <elementGuidId>a6e40754-a111-4549-9c05-a012ed0d2997</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AutomaticPayments-actives</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'AutomaticPayments-actives']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Activos&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bb0174a8-8350-4378-9f3e-9fcb3d9ef0d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AutomaticPayments-actives</value>
      <webElementGuid>6d6d3296-d106-443f-8892-4ed7940d336d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/onlinebanking/AutomaticPayments/AutomaticPayment/Active#AutomaticPayments-index-tabs-content</value>
      <webElementGuid>3a828b9c-88a7-443c-9b04-8ec6b28fcf00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>44b96330-36c5-48f8-bca0-721912b0ae8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d50f66c0-95a4-4edc-8040-d106bf5311c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Activos</value>
      <webElementGuid>3ceee1b4-15b5-48d5-afad-22d0e89b84d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-30297664c8a782d40617f85360fec72e</value>
      <webElementGuid>1dfa0695-82f1-4b4d-a70d-a21cdd20412c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'AutomaticPayments-actives']</value>
      <webElementGuid>67d04a29-609d-4f27-9cae-bacfa03dfa72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'AutomaticPayments-actives']</value>
      <webElementGuid>e84e849c-29d0-4811-bf71-201ead5a08a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'AutomaticPayments-actives' and @href = '/onlinebanking/AutomaticPayments/AutomaticPayment/Active#AutomaticPayments-index-tabs-content' and (text() = 'Activos' or . = 'Activos')]</value>
      <webElementGuid>18fc7075-d993-4600-9c6a-a23ddaf707c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
