<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_validateExpress</name>
   <tag></tag>
   <elementGuidId>701085a2-0fd7-4557-81fc-c80b4eb57643</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#validateExpress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'validateExpress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Validar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>47be98f1-bc94-4a08-89b9-09bb6cb89a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>validateExpress</value>
      <webElementGuid>7bc0d361-856d-446a-8fe4-96c240ce122a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a8cfeb17-3c70-4c98-9f4a-e6ac1bb1a326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>04beacf6-2251-4022-b57d-e7ad7c384ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Validar</value>
      <webElementGuid>7b03527c-d15f-4312-9b98-70497ccec67c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1a355b71e9947c6a5cdea9537172af83</value>
      <webElementGuid>a7a12def-937d-4a15-9983-a40addb4ab9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'validateExpress']</value>
      <webElementGuid>a5b638af-e320-4b42-9f37-67b0736c5ce7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'validateExpress']</value>
      <webElementGuid>e42d387d-8057-4bd2-baa8-ad3099cf909a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'validateExpress' and @type = 'button' and (text() = 'Validar' or . = 'Validar')]</value>
      <webElementGuid>cadd0e84-b46a-4dc1-b682-a5b03e39a8a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
