<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PayExpressContractNumber</name>
   <tag></tag>
   <elementGuidId>27d9bcec-9ff6-465f-97e5-9dc0c3b606a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PayExpressContractNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'PayExpressContractNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PayExpressContractNumber</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ed92b86-c9b2-45b3-8f1d-34959830b757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dfa05f3f-020a-4f45-af1c-d0e6b0e603fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2d46a624-e29b-42ad-87a1-dfc84116d8a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>El campo 'Número de Contrato' contiene caracteres inválidos ó no cumple con la longitud entre 5 y 30 caracteres.</value>
      <webElementGuid>eec34159-8d48-4451-af99-eae26a15f547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^[a-zA-Z0-9\-\.]{5,30}$</value>
      <webElementGuid>834f70a3-2836-479b-ac50-6805c5acffa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>El campo 'Número de Contrato' es requerido.</value>
      <webElementGuid>590b9929-6043-4319-b266-ec7653174156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PayExpressContractNumber</value>
      <webElementGuid>347764a4-bee2-450b-9310-eb7f6b4c88f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PayExpressContractNumber</value>
      <webElementGuid>5e7041bf-f631-4fd4-a1cb-8af89bf27889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1b37685b-e157-4f8e-b00c-53daa5a67a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-79e295860f445f174a8a0b9f0d359403</value>
      <webElementGuid>55a155ca-9dcd-4eea-991e-f28c477217c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'PayExpressContractNumber']</value>
      <webElementGuid>2ac8c294-050d-4fad-8100-2b14dc510b95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'PayExpressContractNumber']</value>
      <webElementGuid>349ed991-63ad-4a16-8738-1858eebc8e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PayExpressContractNumber' and @name = 'PayExpressContractNumber' and @type = 'text']</value>
      <webElementGuid>d0438a5a-b154-4139-b6cf-f470c1f55c0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
