<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AnyAmountPayment</name>
   <tag></tag>
   <elementGuidId>89d0b173-c19e-4e6d-8d30-bdb21ac60f83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AnyAmountPayment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'AnyAmountPayment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#AnyAmountPayment</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a5f8c7c-b020-4433-8054-8b8e644137c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sii-moneyformat form-control valid</value>
      <webElementGuid>4cf15d95-3c88-429a-86f2-5d587dbcf292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>87682c1c-d100-4459-88c2-3f8cba3b5c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field AnyAmountPayment must be a number.</value>
      <webElementGuid>0a21fb31-1b36-4e6e-9bb9-3f0c2f4aa723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>El campo 'Otro Monto' es requerido.</value>
      <webElementGuid>ab5418bd-f8f8-4b6f-8bc7-552393c2128b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AnyAmountPayment</value>
      <webElementGuid>d5c73017-ab4f-4927-96b3-763a4d742b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>transactionDetails[0].AnyAmountPayment</value>
      <webElementGuid>b0511d92-3609-4d80-b50e-bb34fa62326e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e121f603-a494-4dac-a9c5-d1adb6395f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>844e2a74-a773-4412-9063-abd885f230e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>AnyAmountPayment-error</value>
      <webElementGuid>f108547a-fd2c-45d8-b9a4-4c9aaaef1fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2ed945f2-8bc3-42a4-8733-adab8f43fe5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d57e76098741e1f2575a5acff3fcafec</value>
      <webElementGuid>1ca03272-31f4-4ac3-a618-afcdef98d490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'AnyAmountPayment']</value>
      <webElementGuid>459b54e3-89c4-4fcc-9a5d-e818b5fa90a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'AnyAmountPayment']</value>
      <webElementGuid>40c157f0-54f5-49d8-8ff5-2469996b1945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AnyAmountPayment' and @name = 'transactionDetails[0].AnyAmountPayment' and @type = 'text']</value>
      <webElementGuid>b2ad8f49-618e-4a22-b8cf-bb26ed0d5454</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
