<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ChallengesRequests_0_Challenges_0_SIICHKAn</name>
   <tag></tag>
   <elementGuidId>12361a24-b740-477a-94b5-9b13191364b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;ChallengesRequests\[0\]\.Challenges\[0\]\.__SIICHKAnswer&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'ChallengesRequests[0].Challenges[0].__SIICHKAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ChallengesRequests_0__Challenges_0____SIICHKAnswer</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5620ecd8-8cac-4dbb-a962-0a54fdf11c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>d60babf3-cf51-4c9b-ac01-9c2693176070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autofocus</name>
      <type>Main</type>
      <value>autofocus</value>
      <webElementGuid>93caec11-8a2a-4fd4-9fe8-4063a9fe2eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>62677ca0-762f-435f-8ba7-9bfe8ab39b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f73f111f-8d74-435e-9db0-55320c6aa18d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>El campo 'Respuesta de Seguridad' de tener un mínimo '2' y un máximo de '80' de longitud.</value>
      <webElementGuid>c6159f2a-10cb-4281-86bf-36ca14bb2fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^.{2,80}$</value>
      <webElementGuid>abad3c79-3cb9-4f88-811f-641afd2aa711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>El campo 'Respuesta de Seguridad' es requerido.</value>
      <webElementGuid>2073dee0-fb8e-4233-9676-5b2fdc2cdedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ChallengesRequests_0__Challenges_0____SIICHKAnswer</value>
      <webElementGuid>b5738d86-1bda-4f70-918c-111f42da15dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ChallengesRequests[0].Challenges[0].__SIICHKAnswer</value>
      <webElementGuid>19561ac0-3014-43c1-a463-9dc7c723330e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b058dde1-3200-4790-96bb-d2d452b974dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d4c29927d25e623d071139d8bbcb9f7b</value>
      <webElementGuid>5debbfee-15be-4a19-a5bb-68014dea2461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'ChallengesRequests[0].Challenges[0].__SIICHKAnswer']</value>
      <webElementGuid>5dcee74d-6fc5-4a27-89fa-421ec9cbef0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'ChallengesRequests[0].Challenges[0].__SIICHKAnswer']</value>
      <webElementGuid>b586c5f2-c7ba-49cf-b854-93bbc133f8e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ChallengesRequests_0__Challenges_0____SIICHKAnswer' and @name = 'ChallengesRequests[0].Challenges[0].__SIICHKAnswer' and @type = 'text']</value>
      <webElementGuid>6621cb1a-ad64-420a-9873-e0b06293c5ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
