<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Otro Monto</name>
   <tag></tag>
   <elementGuidId>86407b60-0978-4610-b107-75b9835e3a0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ANY_AMOUNT_PAYMENT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'ANY_AMOUNT_PAYMENT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Otro Monto&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cfb5dbb3-94af-4fda-8aa9-6bef9e4d951a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>eaf0e0f3-3d11-4f0b-8773-6cb86107a5e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ANY_AMOUNT_PAYMENT</value>
      <webElementGuid>2eb77135-6548-40b6-aa47-f067009a7fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>transactionDetails[0].AmountPayType</value>
      <webElementGuid>11329c0e-1ee4-414a-a73b-9a2f190bccaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4be02b9d-52fb-4f49-b232-7c3ddde3f948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ANY_AMOUNT_PAYMENT</value>
      <webElementGuid>b25f5c52-a510-435c-9f88-282863741ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid</value>
      <webElementGuid>2e4fba55-233b-49e5-82ae-4310dd46f9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-2550b1445521b9848d6497b180d13a9e</value>
      <webElementGuid>069dbfe4-c96b-46b4-ba2d-69ad0bdc2cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'ANY_AMOUNT_PAYMENT']</value>
      <webElementGuid>3dc259d6-39de-41bf-be3b-f1bd2c28acdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'ANY_AMOUNT_PAYMENT']</value>
      <webElementGuid>16b08a69-34f7-4f6c-be30-0f9cef96e66f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@checked = 'checked' and @id = 'ANY_AMOUNT_PAYMENT' and @name = 'transactionDetails[0].AmountPayType' and @type = 'radio']</value>
      <webElementGuid>b6057d78-66bc-4a82-b935-09f37ac0f091</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
