<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_(Code_3000)</name>
   <tag></tag>
   <elementGuidId>641826c0-1607-4883-a3e3-5f14f1fd9d94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.modal-body > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' modal-body ')]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;(Code:3000)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d3687e35-286a-43e7-a52f-0e6b0eab2cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    (Code:3000)
                </value>
      <webElementGuid>0562001d-261d-4de3-8081-ee155be3f53f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-2c3e376c1714f33eb2e686c7191807bf</value>
      <webElementGuid>83fc52f3-37b0-42c6-910a-20eca5886eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' modal-body ')]/p</value>
      <webElementGuid>6dd0faf1-2286-49f6-a0d2-dd58c7af82ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' modal-body ')]/p</value>
      <webElementGuid>191dbf6a-ca99-4f57-b6b4-d08821657d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '
                    (Code:3000)
                ' or . = '
                    (Code:3000)
                ')]</value>
      <webElementGuid>316c8caf-c89d-432e-a04b-d0ffab7f3be2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
