<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_trx-comment</name>
   <tag></tag>
   <elementGuidId>31d41ef1-9715-42a9-aa04-9ee3abfd7413</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#trx-comment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'trx-comment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#trx-comment</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2421a524-fec8-457f-9846-5326b8913623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7ee63d03-f856-4b7e-921d-fc1e12f31fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>467df280-afbb-41cd-8b21-13d6741da58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a4527b62-1571-4499-bc20-1e2d98e831c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>La longitud del valor en el campo 'Descripción' es mayor a la permitida de '100' caracteres.</value>
      <webElementGuid>40aec081-11d6-43c0-8e62-09c8d34c00bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>7dd89422-ca0b-463b-9d11-abc5a78fe33a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>El campo 'Descripción' contiene caracteres inválidos.</value>
      <webElementGuid>81b462b2-b867-4141-b4fe-155f4f355a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\-., ]*$</value>
      <webElementGuid>658663ee-80fa-477f-9353-5e11febbf05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>trx-comment</value>
      <webElementGuid>318b17c1-7ad2-4a72-9896-ef56ccb2f58e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>transactionDetails[0].Description</value>
      <webElementGuid>98d2d844-b4dd-4ac2-9a2b-667818de899b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>2e9c05b4-cb3c-427e-a58b-f79eefbb0ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-63e9e9508563b048293213c0fcfbd24a</value>
      <webElementGuid>6352a5ee-4880-43d7-b2ed-f527c43d5c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'trx-comment']</value>
      <webElementGuid>865d0236-17de-4f23-90b1-fdc8e720259b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'trx-comment']</value>
      <webElementGuid>1052b55c-5da7-458a-9df2-c3a08efa7887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'trx-comment' and @name = 'transactionDetails[0].Description']</value>
      <webElementGuid>729bbb7e-2b01-49c9-8a13-ddb2bec4bdc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
