<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Usuario</name>
   <tag></tag>
   <elementGuidId>6cef4b66-0873-4e23-a2b6-a1024b5b7f23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UserNameP</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'UserNameP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Usuario&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39be1905-4114-43a9-ac35-d84696c9a8b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>UserName-Addon-Personal</value>
      <webElementGuid>9433466c-6263-4284-b695-b1be564b211c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3f696394-817b-4911-9cb2-f96f31716057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qwerty form-control UserName</value>
      <webElementGuid>20504941-79e2-45ae-9abd-1a85adc4ca8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7126b9f2-eb99-4f65-9372-95a7d9721741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>El campo 'Usuario' solo puede contener letras, números, '-' y tener un rango entre 3 y 30 caracteres.</value>
      <webElementGuid>424464d6-b8bb-4270-8ad9-c47ab6eff302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^([a-zA-ZñÑ_\.0-9 ]{3,30})$</value>
      <webElementGuid>404dd383-3603-414c-aef0-3d2366807ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>El campo 'Usuario' es requerido.</value>
      <webElementGuid>822c2412-6e78-42f7-86f8-19c3af982197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UserNameP</value>
      <webElementGuid>d9b58066-2bb1-4c0f-a0d0-0fdd05aa2cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UserName</value>
      <webElementGuid>57f16d1d-d0d4-40d7-9aa0-da37f13e5961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Usuario</value>
      <webElementGuid>4ebc1dcc-eac8-4711-bc40-11a4dba80f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>515843d8-6e67-424c-b0bc-7f64bc7ef644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d9f3cab974f072961d848d0899d0f31c</value>
      <webElementGuid>dd43fe5c-0c38-48c8-85aa-80edd31cc392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'UserNameP']</value>
      <webElementGuid>a9fb42a0-6d56-4ffb-992f-7cc41e1b9dad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'UserNameP']</value>
      <webElementGuid>9d175598-5e9e-43e3-b421-560da94595bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UserNameP' and @name = 'UserName' and @placeholder = 'Usuario' and @type = 'text']</value>
      <webElementGuid>fb9538ab-b2cf-48ff-b69e-4040221fd13d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
