<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_taxesPayments</name>
   <tag></tag>
   <elementGuidId>3dcea277-fdff-407d-a0c0-d72ecb33f380</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'taxesPayments']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#taxesPayments</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Impuestos&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>57514f1c-ea5c-4671-9b17-17632a7aacf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>taxesPayments</value>
      <webElementGuid>685f5ce7-98e2-48d3-8742-c25f3f177083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/onlinebanking/IndividualPayments/TaxesPayments?_resetCache=False&amp;tabId=&amp;accountFrom=&amp;accountTo=#payments-service-index-tabs-content</value>
      <webElementGuid>a836e8a3-0c75-45d5-a468-43badfcb2ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>6d8e0579-1eac-4af3-afd2-d084401d7504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Impuestos</value>
      <webElementGuid>17e24985-dc6c-45ba-9195-1488b5415331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a01805bb4a75791f141087cb551a9e5d</value>
      <webElementGuid>d9668510-4eb3-4b99-9b60-c8812ab91d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'taxesPayments']</value>
      <webElementGuid>9377a53b-3087-426a-8ecf-51236b5392fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'taxesPayments']</value>
      <webElementGuid>d108fbc8-0a3f-46f7-89a0-5a9716f58f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'taxesPayments' and @href = '/onlinebanking/IndividualPayments/TaxesPayments?_resetCache=False&amp;tabId=&amp;accountFrom=&amp;accountTo=#payments-service-index-tabs-content' and (text() = 'Impuestos' or . = 'Impuestos')]</value>
      <webElementGuid>e34d9aa3-2807-4ed2-8dd4-50ac8adec0bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
