<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_validateExpress</name>
   <tag></tag>
   <elementGuidId>93b8305a-f5ac-402a-8b58-baca493eae1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#validateExpress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'validateExpress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Validar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>69fbce62-1107-4344-abe1-af1bd581a0b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>validateExpress</value>
      <webElementGuid>2872d020-0c94-4b7b-8006-e3e197ef61da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0412ba2e-b6ef-4a90-83b6-1a0debb927a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>338e6cf7-8a57-44f6-84c0-386fe0426223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Validar</value>
      <webElementGuid>6257bdd1-499c-43cc-a4e2-d3629eeac2ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1a355b71e9947c6a5cdea9537172af83</value>
      <webElementGuid>e8dcfa6b-a5f8-4195-8d18-891f169d831c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'validateExpress']</value>
      <webElementGuid>b4a56f06-22af-4bce-ad54-fe2b07d1df5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'validateExpress']</value>
      <webElementGuid>218c6255-7e22-41e3-bbf2-2f3de151b1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'validateExpress' and @type = 'button' and (text() = 'Validar' or . = 'Validar')]</value>
      <webElementGuid>476057d2-33be-4483-a385-879e2b5c94c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
