<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_icon-eye-open</name>
   <tag></tag>
   <elementGuidId>56f49c97-daa6-4e64-b170-d511d8ee602f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#showAdditionalInfoExpress i</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'showAdditionalInfoExpress']//i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>74b5adfb-df30-4381-b5d6-0f4479cc35b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-eye-open</value>
      <webElementGuid>9fa6d720-3bdf-4904-b5dd-1e368c9a9778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-46f6e5c6c2212dc6d30bff9e1e369960</value>
      <webElementGuid>c090d76a-4163-441d-8bd1-ed2f2796ccf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'showAdditionalInfoExpress']//i</value>
      <webElementGuid>60d8bc7e-f483-45a6-b7fe-00eb4a5ebfd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'showAdditionalInfoExpress']//i</value>
      <webElementGuid>eff379f8-dcbf-4245-9d7b-7d32083c43e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
