<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_addTaxPayment</name>
   <tag></tag>
   <elementGuidId>19c3ada1-a2da-4e1a-8965-41db2e0cfcbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'addTaxPayment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addTaxPayment</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Validar y Agregar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9bf6786c-b51e-4fe0-9fa0-d6a70ba1592a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addTaxPayment</value>
      <webElementGuid>dc7dcfb0-cd3a-42f9-babc-f4d5c9e2c536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>78dbf6a9-7494-4091-9345-3bd6124ce129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Validar y Agregar</value>
      <webElementGuid>0235a380-134a-4668-b2da-27ca202cdc82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>50f9e42b-2a0f-4a34-93c6-d11ebfe7db49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fa6e35d63136750c87ccc2ba4490299b</value>
      <webElementGuid>3972decb-550e-47c3-8d6b-e1bac89ce863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'addTaxPayment']</value>
      <webElementGuid>78a48063-d251-42b7-b79b-b0ff1fc80257</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'addTaxPayment']</value>
      <webElementGuid>b947420c-11e2-4b15-8795-d954ff71fe45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addTaxPayment' and @type = 'submit']</value>
      <webElementGuid>d218d815-50ac-40e3-a426-3c302c2e8e3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
