<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ChallengesRequests_0_Challenges_0_SIICHKAn</name>
   <tag></tag>
   <elementGuidId>42634d96-8c1f-4a2a-912e-302e8197a545</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;ChallengesRequests\[0\]\.Challenges\[0\]\.__SIICHKAnswer&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'ChallengesRequests[0].Challenges[0].__SIICHKAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ChallengesRequests_0__Challenges_0____SIICHKAnswer</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d5690c5-e437-4af4-9d0d-8497627e4d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>7ebcc78a-9d4e-4e02-9e50-49ed0c0d0215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autofocus</name>
      <type>Main</type>
      <value>autofocus</value>
      <webElementGuid>895080f2-2f60-4def-af79-a45f2486a8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>84a671a7-54b7-4913-8e69-a476236d7034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e915084e-0566-404d-a25b-d0dc54cd7619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>El campo 'Respuesta de Seguridad' de tener un mínimo '2' y un máximo de '80' de longitud.</value>
      <webElementGuid>1f01269f-1d18-4d7a-95a1-2586a7e4e490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^.{2,80}$</value>
      <webElementGuid>7e5ea897-1117-4f9a-af2c-1d61b3382dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>El campo 'Respuesta de Seguridad' es requerido.</value>
      <webElementGuid>346993aa-cbe6-42ef-84e7-5ff0caeb462b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ChallengesRequests_0__Challenges_0____SIICHKAnswer</value>
      <webElementGuid>5c8c6813-1c54-44aa-a9b3-a675c59b831c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ChallengesRequests[0].Challenges[0].__SIICHKAnswer</value>
      <webElementGuid>51c26839-3b8c-4859-bc9e-1eff08fa36fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6fc16245-7807-4704-8a15-a12abd913d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d4c29927d25e623d071139d8bbcb9f7b</value>
      <webElementGuid>f53a833c-2c1d-47a3-a08a-63d370c69e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'ChallengesRequests[0].Challenges[0].__SIICHKAnswer']</value>
      <webElementGuid>535bdd3a-ea82-4bda-b96f-c61b0c2da05a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'ChallengesRequests[0].Challenges[0].__SIICHKAnswer']</value>
      <webElementGuid>250fc811-3947-4dc5-b0a0-cfec0ab43dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ChallengesRequests_0__Challenges_0____SIICHKAnswer' and @name = 'ChallengesRequests[0].Challenges[0].__SIICHKAnswer' and @type = 'text']</value>
      <webElementGuid>67a90c0f-0551-4ebb-bb10-6d6d087d3bcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
