<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Otro Monto</name>
   <tag></tag>
   <elementGuidId>dd0350fc-dfd3-4599-ac1c-9bc0fa199da0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ANY_AMOUNT_PAYMENT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'ANY_AMOUNT_PAYMENT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Otro Monto&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6179225b-1479-4ffc-a2e1-be8508c94975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>46565cf0-032f-44fa-87b9-2b225326d775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ANY_AMOUNT_PAYMENT</value>
      <webElementGuid>39adf415-4bb0-4e95-af9a-7f09640616fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>transactionDetails[0].AmountPayType</value>
      <webElementGuid>df15b284-55bf-4f16-b6b3-007e1750e0ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>abd3603a-87a2-4d45-9b1c-33b2148d7d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ANY_AMOUNT_PAYMENT</value>
      <webElementGuid>83539965-d113-478d-8f98-052299b399af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid</value>
      <webElementGuid>681250ab-7212-4b33-a92c-c5dd5e83aa75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-2550b1445521b9848d6497b180d13a9e</value>
      <webElementGuid>d371a057-0871-4338-bf4d-b0f5a7329c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'ANY_AMOUNT_PAYMENT']</value>
      <webElementGuid>f2ef634e-f892-4bd9-9d6e-9456cbcd480c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'ANY_AMOUNT_PAYMENT']</value>
      <webElementGuid>4b704324-37af-432f-bc6b-276661ed31f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@checked = 'checked' and @id = 'ANY_AMOUNT_PAYMENT' and @name = 'transactionDetails[0].AmountPayType' and @type = 'radio']</value>
      <webElementGuid>e9c4c441-84e1-462c-b1b3-b7db616aa716</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
