<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_frmContinue</name>
   <tag></tag>
   <elementGuidId>37186ac2-17e6-49c9-a7aa-7e7d16d1ff9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmContinue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'frmContinue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Continuar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae95cd2b-10c7-47ca-aa19-6895cfde5d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>cfecc39b-31f1-42b0-8096-41268fbe9b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmContinue</value>
      <webElementGuid>1147c101-87b6-40ac-958c-35779c9d8525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>eebd9332-b850-4c06-a7a8-525571a83597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Continuar</value>
      <webElementGuid>acc48d5d-007d-420e-9370-8d8a8e4f8bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-634713742577d44ac57c0ed338641ccd</value>
      <webElementGuid>8bf13b6d-b8f3-40e6-8e94-3e81fa4bc2ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'frmContinue']</value>
      <webElementGuid>7377a1d6-a273-461d-99fa-c7d204e6be72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'frmContinue']</value>
      <webElementGuid>d815ff36-b52b-417f-8f04-fd286f1ddb9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'frmContinue']</value>
      <webElementGuid>a5394221-4c04-466c-bce5-a5ab5c5e1228</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
