<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PayExpressContractNumber</name>
   <tag></tag>
   <elementGuidId>546c5595-4d65-43cf-91d0-fabd11495008</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PayExpressContractNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'PayExpressContractNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PayExpressContractNumber</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e875b49f-e52c-4f93-b8aa-ff99e398fe0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>acf7a0d5-53d1-4c31-8396-8a1c994eddc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ea9d4455-8085-412d-9643-fd42cd44f994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>El campo 'Número de Contrato' contiene caracteres inválidos ó no cumple con la longitud entre 5 y 30 caracteres.</value>
      <webElementGuid>a8a220f8-5e89-4e76-9719-258adf34109c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^[a-zA-Z0-9\-\.]{5,30}$</value>
      <webElementGuid>966c6e46-9dbd-47bd-aefd-c6d9414a817b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>El campo 'Número de Contrato' es requerido.</value>
      <webElementGuid>178a3b50-6841-4588-a86f-d2a955b63234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PayExpressContractNumber</value>
      <webElementGuid>21a91a9d-337f-4a16-9470-b8fd38f3b3bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PayExpressContractNumber</value>
      <webElementGuid>ba82679d-579a-446d-b987-6dcecb1434c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fd49d17c-9df1-4c2f-aed8-75cfd3f3d709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-79e295860f445f174a8a0b9f0d359403</value>
      <webElementGuid>d893da71-f0f9-478f-8efb-e25015ba1b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'PayExpressContractNumber']</value>
      <webElementGuid>5bfd77d6-74fe-45ff-9b81-33937f83a55b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'PayExpressContractNumber']</value>
      <webElementGuid>281f890f-7d48-40d1-9723-3f8d09dd67b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PayExpressContractNumber' and @name = 'PayExpressContractNumber' and @type = 'text']</value>
      <webElementGuid>d47842d4-7a2f-4695-bffc-e22d26e73431</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
