<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AnyAmountPayment</name>
   <tag></tag>
   <elementGuidId>1c2603bf-e4c3-4d16-9900-cbed77a7dc5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AnyAmountPayment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'AnyAmountPayment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#AnyAmountPayment</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93af807a-67f9-407d-a355-04a5910e1c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sii-moneyformat form-control valid</value>
      <webElementGuid>75e2b915-31c9-4c27-9145-c2e1ff141830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1519f6f1-f1ea-4f69-889e-f8721bddb301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field AnyAmountPayment must be a number.</value>
      <webElementGuid>3c9f1943-18b3-4e44-870e-3d2e78b36403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>El campo 'Otro Monto' es requerido.</value>
      <webElementGuid>c6a24758-f144-464e-805c-230576b467db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AnyAmountPayment</value>
      <webElementGuid>ff2b052e-1f20-4f09-916c-7847e54296e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>transactionDetails[0].AnyAmountPayment</value>
      <webElementGuid>66e5460e-4fde-4281-ae74-e6484d7e2c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eaa765b1-2e1f-4e71-9761-5464e3dac0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5256516e-bf9c-46e0-b5a4-2a821be3a6cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>AnyAmountPayment-error</value>
      <webElementGuid>9d3efceb-d3b7-4340-9e75-b6db8e274d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>103d73b0-9b40-4112-9924-795fee6f8bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d57e76098741e1f2575a5acff3fcafec</value>
      <webElementGuid>66eee769-fbdb-4125-baeb-30389fe9cf5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'AnyAmountPayment']</value>
      <webElementGuid>2b0dbb04-9004-4b9a-b588-51857320e923</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'AnyAmountPayment']</value>
      <webElementGuid>fde06859-ac79-4de0-9ca6-b79703336329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AnyAmountPayment' and @name = 'transactionDetails[0].AnyAmountPayment' and @type = 'text']</value>
      <webElementGuid>311471f0-5225-4978-895b-9eb215105be7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
