<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Usuario</name>
   <tag></tag>
   <elementGuidId>87d84e94-3366-429e-b73e-15a7287d4cd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'UserNameP']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#UserNameP</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Usuario&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39b08a72-afb6-4085-8d0a-b24be24e2d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>UserName-Addon-Personal</value>
      <webElementGuid>644c9547-ffc5-41f6-ab09-40ae818b9d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9dc00d4e-60b4-422b-b623-3cbf1f0c6ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qwerty form-control UserName</value>
      <webElementGuid>49a7cf95-228e-41df-94af-3fef3f14830e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d4024a2c-a493-4481-bc81-9870875740bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>El campo 'Usuario' solo puede contener letras, números, '-' y tener un rango entre 3 y 30 caracteres.</value>
      <webElementGuid>ddfb1f11-2d4e-4b94-8192-198f29db14ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^([a-zA-ZñÑ_\.0-9 ]{3,30})$</value>
      <webElementGuid>09ff3c56-bfc3-4082-9af2-31831c0632bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>El campo 'Usuario' es requerido.</value>
      <webElementGuid>9c19161d-62f1-4ed9-915a-276e5bd5cf23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UserNameP</value>
      <webElementGuid>a450d792-6682-40e8-8c02-6e8022c355d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UserName</value>
      <webElementGuid>1638b4c4-cb94-4193-bb64-16b56b199ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Usuario</value>
      <webElementGuid>e759ddb0-b4c0-4f5f-9b2c-876b8a546884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c251c490-f5fc-42b3-b6ef-24376a8dcda5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d9f3cab974f072961d848d0899d0f31c</value>
      <webElementGuid>e7d6e7c0-e835-4e69-9f70-95eef2af0fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'UserNameP']</value>
      <webElementGuid>afe0b352-f182-40db-a820-d7c4e41568a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'UserNameP']</value>
      <webElementGuid>0656e6ab-d08e-4db9-bc89-c9207cc9d9c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UserNameP' and @name = 'UserName' and @placeholder = 'Usuario' and @type = 'text']</value>
      <webElementGuid>bfbac508-a28e-470c-84f9-85e0f856455a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
