<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_CompanyTo</name>
   <tag></tag>
   <elementGuidId>70caf611-8d23-4119-85e4-f41b92c02772</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'CompanyTo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CompanyTo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#CompanyTo</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a62f6856-dac3-4228-bc07-13f7dcc35301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bc6b06af-a41d-4f42-8a0b-534cd677263b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c2202369-3bb7-4c8a-844d-5c2f150d6668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>El campo 'Empresa' es requerido.</value>
      <webElementGuid>13dbb493-98bc-475a-a286-31ed7308a52c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CompanyTo</value>
      <webElementGuid>69ccde49-5474-4cca-a8d5-19e7da87dae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TaxCompanyTo.CompanySelected</value>
      <webElementGuid>db359da2-d3e7-471e-adf3-4eb2b91a388a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione una EmpresaDGADGIITSSINFOTEPDGII_Marbetes</value>
      <webElementGuid>aacf924f-18d3-4b63-b337-3c4163d46617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-84c0074f7f0356af183b7cd3870004d3</value>
      <webElementGuid>bda19e81-a9d8-493a-8673-519f872a29c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'CompanyTo']</value>
      <webElementGuid>f7959a9f-98e2-4137-8ca1-84244721e914</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'CompanyTo']</value>
      <webElementGuid>9046eafb-6268-44cb-9fb6-6fa5e1cbc97e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'CompanyTo' and @name = 'TaxCompanyTo.CompanySelected' and (text() = 'Seleccione una EmpresaDGADGIITSSINFOTEPDGII_Marbetes' or . = 'Seleccione una EmpresaDGADGIITSSINFOTEPDGII_Marbetes')]</value>
      <webElementGuid>74e0cf5c-41b3-4f1c-b739-b12d156f9aee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
