<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_trx-comment</name>
   <tag></tag>
   <elementGuidId>c9c72e1c-c373-4e15-8502-2792b08bbd01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#trx-comment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'trx-comment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#trx-comment</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>90c5f00e-54c5-4b56-a0e9-b8bb55be1a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control valid</value>
      <webElementGuid>e80bbd14-ec13-4978-a881-859b1ca1eeaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>4e4e867f-b267-4c97-891e-337afb471891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>90b5f034-5327-44bb-a6b5-d770f83ecf61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>La longitud del valor en el campo 'Descripción' es mayor a la permitida de '100' caracteres.</value>
      <webElementGuid>7bee614f-573f-4a00-84ec-7f0a87d19d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>3577acf7-02ed-4f91-b0d4-d5cfd191ec15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>El campo 'Descripción' contiene caracteres inválidos.</value>
      <webElementGuid>f55455c2-e059-454c-9c6b-fa14d6ea1c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\-., ]*$</value>
      <webElementGuid>c3b56843-0368-49ff-9eae-fe2c571684fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>trx-comment</value>
      <webElementGuid>18f300bc-6ce5-4039-9322-22ffe8ec0cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>transactionDetails[0].Description</value>
      <webElementGuid>0ac23877-ef45-4ec1-8656-c182c9b830ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>4d78dcd4-4783-4434-817c-8c1bceb9db62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>trx-comment-error</value>
      <webElementGuid>3feede81-3153-4fda-ac2e-2147574a4640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e3f244ad-b368-4d23-9f31-38845e17b45b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-63e9e9508563b048293213c0fcfbd24a</value>
      <webElementGuid>12749ed5-cf79-4996-b78b-d00384cc49ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'trx-comment']</value>
      <webElementGuid>03b8e24f-0287-4921-92a2-e04a4a7d8717</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'trx-comment']</value>
      <webElementGuid>df6efbd0-2fab-4d92-858a-74d261e94e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'trx-comment' and @name = 'transactionDetails[0].Description']</value>
      <webElementGuid>7690cd6c-728e-484e-9d4c-610cd4eecc46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
