<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_trx-comment</name>
   <tag></tag>
   <elementGuidId>c9c72e1c-c373-4e15-8502-2792b08bbd01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'trx-comment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#trx-comment</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'trx-comment' and @name = 'TaxCompanyTo.Description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#trx-comment</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8fbc5f0c-5434-4f09-8fbb-b7efe28a2d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fb83bac0-b9b5-41b6-b6d9-400bad635e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>be7a2dce-c6dc-439b-bdd3-ff0995baa2cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>56cdafb4-393b-48c8-ae29-fb5a90debfb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>La longitud del valor en el campo 'Descripción' es mayor a la permitida de '100' caracteres.</value>
      <webElementGuid>df45ec3e-a1bd-4345-a10e-06839c4ba67f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>b3f07200-6b32-4ab7-8db2-ddcc5745532e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>El campo 'Descripción' contiene caracteres inválidos.</value>
      <webElementGuid>686cc9c0-4ee2-4da4-9480-6d13495078e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\-., ]*$</value>
      <webElementGuid>b025dc8f-ab6e-457b-890b-fbcc7d17fd2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>trx-comment</value>
      <webElementGuid>d3a3e19a-6e1b-4d80-aeb3-ec706d61969e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TaxCompanyTo.Description</value>
      <webElementGuid>0193d777-4f59-4cf5-9e50-4d48d824a5ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>f52625e8-d91b-49c0-b44e-042ec7c73c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>trx-comment-error</value>
      <webElementGuid>3feede81-3153-4fda-ac2e-2147574a4640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e3f244ad-b368-4d23-9f31-38845e17b45b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-63e9e9508563b048293213c0fcfbd24a</value>
      <webElementGuid>66a50f08-2239-485d-bd3d-8c47b50d6aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'trx-comment']</value>
      <webElementGuid>884e45ee-c224-460a-aa9e-8db297fe4572</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'trx-comment']</value>
      <webElementGuid>7f2e3012-6bbd-4c00-8694-9dfd26da53c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'trx-comment' and @name = 'TaxCompanyTo.Description']</value>
      <webElementGuid>06454647-e733-4196-bb04-b2488f4a4291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'trx-comment' and @name = 'transactionDetails[0].Description']</value>
      <webElementGuid>7690cd6c-728e-484e-9d4c-610cd4eecc46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
